[build]
  command = "npm ci --prefix client && npm run build --prefix client"
  publish = "client/dist"
  functions = "client/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
